# Generated by Django 3.2.2 on 2023-06-03 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=200)),
                ('intro', models.CharField(max_length=400)),
                ('people', models.CharField(blank=True, max_length=200)),
                ('funding', models.CharField(default='NA', max_length=20)),
                ('dep', models.CharField(default='NA', max_length=20)),
                ('approved', models.BooleanField(default=False)),
                ('emails', models.CharField(max_length=200)),
                ('creator_id', models.IntegerField()),
            ],
            options={
                'db_table': 'labs',
            },
        ),
    ]
