# Generated by Django 3.2.2 on 2023-07-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_lab_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='intro',
            field=models.TextField(),
        ),
    ]
