# Generated by Django 3.2.2 on 2023-07-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20230712_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='uid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
