# Generated by Django 3.2.2 on 2023-07-12 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_userprofile_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='up_id',
            new_name='id',
        ),
    ]
