# Generated by Django 4.2.1 on 2023-05-15 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='lab',
        ),
        migrations.AddField(
            model_name='comment',
            name='labid',
            field=models.ForeignKey(db_column='labid', default=1, on_delete=django.db.models.deletion.CASCADE, to='api.lab'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='comment',
            table='comments',
        ),
        migrations.AlterModelTable(
            name='lab',
            table='labs',
        ),
    ]
