# Generated by Django 4.2.1 on 2023-05-19 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0002_delete_user_remove_comment_lab_comment_labid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('rate', models.IntegerField()),
                ('contact', models.EmailField(max_length=254)),
                ('intro', models.TextField()),
                ('labname', models.CharField(max_length=100)),
                ('labid', models.ForeignKey(db_column='labid', on_delete=django.db.models.deletion.CASCADE, to='api.lab')),
            ],
        ),
    ]
