# Generated by Django 3.2.2 on 2023-06-14 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SavedLabs2',
        ),
    ]
