# Generated by Django 3.2.2 on 2023-08-25 16:07

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lab', '0003_alter_lab_intro'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('course', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('rate_type', models.CharField(choices=[('credit', 'Credit'), ('number', 'Number'), ('volunteer', 'Volunteer'), ('flexible', 'Flexible')], default='number', max_length=10)),
                ('rate', models.FloatField(blank=True, null=True)),
                ('contact', models.EmailField(max_length=254)),
                ('intro', models.TextField()),
                ('labname', models.CharField(max_length=100)),
                ('lablink', models.URLField()),
                ('workhoursselection', models.CharField(choices=[('< 10 hours', '< 10 hours'), ('10-20 hours', '10-20 hours'), ('20-30 hours', '20-30 hours'), ('> 30 hours', '> 30 hours'), ('flexible', 'Flexible')], max_length=20)),
                ('workmodel', models.CharField(choices=[('Onsite', 'Onsite'), ('Remote', 'Remote'), ('Hybrid', 'Hybrid'), ('Unsure', 'Unsure')], max_length=20)),
                ('consecutivesemestersselect', models.CharField(choices=[('A semester', 'A semester'), ('Two semesters', 'Two semesters'), ('Academic year', 'Academic year'), ('Summer', 'Summer')], max_length=20)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved', models.BooleanField(default=False)),
                ('labid', models.ForeignKey(db_column='labid', on_delete=django.db.models.deletion.CASCADE, to='lab.lab')),
                ('oidc_auth_user', models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
