import myLogo from './myLogo.png'; 
import corgi from './corgi.png';
import umich from './umich.png';
import logo from './logo.png';
import formalLogo from './mlabhub_icon512.png';
import formalLogo192 from './mlabhub_icon192.png';
export const MLabHubLogo512 = formalLogo;
export const MLabHubLogo192 = formalLogo192;
export const logoImg = myLogo;
export const corgiImg = corgi;
export const umichImg = umich;
export const appLogo = logo;
