# Generated by Django 3.2.2 on 2023-06-13 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oidc_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
