PRAGMA foreign_keys = ON;
CREATE TABLE labs(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(20) NOT NULL,
    link VARCHAR(20) NOT NULL,
    intro VARCHAR(200) NOT NULL,
    people VARCHAR(100)
);

CREATE TABLE comments(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    labid INTEGER NOT NULL,
    rating INTEGER NOT NULL, 
    name VARCHAR(20) NOT NULL,
    word VARCHAR(200) NOT NULL,
    FOREIGN KEY (labid) REFERENCES labs(id)
);